In [1]:
import torch

In [2]:
torch.randn((2, 3))

tensor([[ 0.1164, -0.1231,  0.7231],
        [ 0.2934, -0.9575, -0.4493]])

In [3]:
torch.randn((2, 3))

tensor([[ 0.2711,  2.5537, -1.4657],
        [ 1.2710, -0.1657, -1.1504]])

#### Seeded randomness

In [4]:
gen0 = torch.Generator().manual_seed(0)
gen1 = torch.Generator().manual_seed(0)

In [5]:
torch.rand(2, generator=gen0), torch.rand(3, generator=gen0)

(tensor([0.4963, 0.7682]), tensor([0.0885, 0.1320, 0.3074]))

In [6]:
torch.rand(3, generator=gen1), torch.rand(2, generator=gen1)

(tensor([0.4963, 0.7682, 0.0885]), tensor([0.1320, 0.3074]))

#### Junk

In [7]:
x = torch.randn((2, 3), gen=None)
x

TypeError: randn() received an invalid combination of arguments - got (tuple, gen=NoneType), but expected one of:
 * (tuple of ints size, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)
 * (tuple of ints size, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)
