# Docs
### Official PyTorch
- https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html
- https://pytorch.org/docs/stable/nn.html#module

### Blog posts
- https://jhui.github.io/2018/02/09/PyTorch-nn-modules-API-summary/


In [1]:
import torch
import torch.optim as optim
import torch.nn as nn

In [2]:
class DummyNet(nn.Module):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.layer = nn.Linear(3, 2)  # inherits from Module!

    def forward(self, x):
        x = x.view(x.size(0), -1)
        return self.layer(x)

In [3]:
net = DummyNet()

In [4]:
layer1 = net._modules['layer']
layer1

Linear(in_features=3, out_features=2, bias=True)

In [5]:
layer1.weight.data

tensor([[-0.3592, -0.0317,  0.0346],
        [ 0.2786, -0.0380,  0.5510]])

In [6]:
net.layer.weight.data

tensor([[-0.3592, -0.0317,  0.0346],
        [ 0.2786, -0.0380,  0.5510]])

In [7]:
x = torch.randn(2, 3)
print(x)
out = net(x)
print(net.layer.weight.data)
print(out)

tensor([[ 2.8097, -2.6675,  0.1124],
        [-0.2032,  0.2249,  0.9516]])
tensor([[-0.3592, -0.0317,  0.0346],
        [ 0.2786, -0.0380,  0.5510]])
tensor([[-0.8896,  0.6216],
        [ 0.1298,  0.1349]], grad_fn=<AddmmBackward>)
